#!/bin/bash

# Test root dir
R=/tmp/check-gocryptfs

export TEST_DEV=$R/testdev
export TEST_DIR=$R/testdir

export SCRATCH_DEV=$R/scratchdev
export SCRATCH_MNT=$R/scratchdir

mkdir -p $TEST_DEV $TEST_DIR $SCRATCH_DEV $SCRATCH_MNT

if [ ! -e $TEST_DEV/gocryptfs.conf ]; then
	gocryptfs -init -quiet -extpass "echo test" $TEST_DEV
fi

export PATH=$PATH:/usr/local/bin

./check $*
