#!/bin/bash

echo "fuse-xfstests version $(git rev-parse --short HEAD)"
date -u

# Test root dir
R=/tmp/check-gocryptfs

export FSTYP=fuse.gocryptfs

export TEST_DEV=$R/testdev
export TEST_DIR=$R/testdir

export SCRATCH_DEV=$R/scratchdev
export SCRATCH_MNT=$R/scratchdir

mkdir -p $TEST_DEV $TEST_DIR $SCRATCH_DEV $SCRATCH_MNT

export PATH=$PATH:/usr/local/bin

if [ ! -e $TEST_DEV/gocryptfs.conf ]; then
	gocryptfs -init -quiet -scryptn 10 -extpass "echo test" $TEST_DEV || exit
fi

./check $*
