on:
  push:
  pull_request:
  schedule:
    - cron:  '0 12 1 * *' # Every 1st of a month at noon UTC

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
      # Don't cancel everything when one version fails
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: apt-get
      run: |
        sudo apt-get -qq update
        sudo apt-get -qq install xfslibs-dev uuid-dev libtool-bin \
          e2fsprogs automake gcc libuuid1 quota attr libattr1-dev make \
          libacl1-dev libaio-dev xfsprogs libgdbm-dev gawk fio dbench \
          uuid-runtime python3 sqlite3 fuse
    - name: make
      run: make -j $(nproc)
